### ISSUE TITLE
show an example to get H3K4me3 GRanges object

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/EnrichedHeatmap#1]
Hi,

Thanks for making this package, and it looks very useful. I was using [Genomation package](https://www.bioconductor.org/packages/release/bioc/vignettes/genomation/inst/doc/GenomationManual-knitr.html) and this one looks more flexible.

Could you pleases show an example on how you get the H3K4me3 GRanges object (with coverage value in the metadata column) from a bam file?

How do you normalize the matrix? Is it by RPKM, CPM or anything else?

Thanks,
Ming

**Comment by jokergoo** [comment]
Hi Ming,

In the example in the vignette, I only use the coverage while with no normalization yet, since there is only one sample.

I think there are several ways to convert a bam file to a `GRanges` object. The way I used is to use `samtools` and `bedtools genomecov`, like:

```{r}
df = read.table(pipe("samtools view -b bam_file chr | bedtools genomecov -ibam stdin -g genome_file -bg"))
gr = GRanges(seqnames = df[[1]], ranges = IRanges(df[[2]], df[[3]]), coverage = log10(df[[4]]+1))
```

Also, you can check [this GenomicRanges vignette](http://bioconductor.org/packages/devel/bioc/vignettes/GenomicRanges/inst/doc/GenomicRangesHOWTOs.pdf), section **How to compute read coverage** to find out how to calculate coverage in pure R.

Or, if you have done peak calling, you can also use peak files as the input. Since peak files are in BED format, they can be easily converted into GRanges objects.

**Comment by crazyhottommy** [comment]
Thanks for your reply. The reason that I am avoiding using bedtools is that for ChIP-seq, one needs to extend each read (36bp) to the fragment length (~200bp), then count how many read counts in each peak (MACS2 called). One has to convert bam to bed and then extend the bed file to 200bp using bedtools and then count.  see my write up [here](https://github.com/crazyhottommy/ChIP-seq-analysis/blob/master/part1.2_convert_bam2_bigwig.md#why-do-we-need-to-extend-the-reads-to-fragment-length200bp)

I believe I saw in bioconductor (forgot where is it...maybe the Rsubread package), one can extend the the reads to fragment length and then count. 

Ming

**Comment by jokergoo** [comment]
Thanks for the information! I am not that deep into ChIP-seq analysis, but I will read your repository. Btw, I didn't know I already stared your repository.

**Comment by crazyhottommy** [comment]
Hey, I figured it out by looking at the source code of [Genomation](https://codecov.io/github/Bioconductor-mirror/genomation/R/scoreMatrix.R?ref=217ba4abf3c93256e033a145d662a7ff1ca1f4ee)  


#### without extending reads,
```r
library(GenomicRanges)
library(GenomicAlignments)
library(rtracklayer)

peaks<-  import("my_MACS2_peaks.bed")
bam<- "my.bam"

# read in only the reads fall into the peaks
reads<- readGAlignments(bam, param = ScanBamParam(which = peaks))

## it is like RNA-seq data counting reads on exons, we count reads on peaks
so1 <- summarizeOverlaps(features=peaks,
                         reads=bam,
                         ignore.strand=TRUE)
## count data 
head(assay(so1))

## put the count data back to peaks:

mcols(peaks)<- assay(so1)
```

#### extending the reads to 200bp

```r
## turn the reads to GR object
aln<- granges(reads)

## extend from 5' to 3' to 200bp
resize(aln, width = 200, fix="start")

so2 <- summarizeOverlaps(features=gr,
                         reads=aln,
                         ignore.strand=TRUE)

mcols(peaks)<- assay(so2)
```

Post it here to keep a note for myself as well!

Best,
Ming

**Comment by yuxuth** [comment]
Thank you Tommy for sharing the code. I wonder can I use the bedgraph file generated by macs2 `-B --SPMR` as the signal file ? macs2 has done the read extending and shift. @crazyhottommy

**Comment by crazyhottommy** [comment]
@yuxuth see if you can read in that bedgraph as GRanges using rtracklayer. if not, you can convert it to bigwig and read in as coverage 

```r
RAS_1475.H3K4me3<- import("bigwigs/RAS_1475-H3K4me3.sorted.bw", format = "bigWig", which = H3K4me3.10kb.peak)
```

**Comment by yuxuth** [comment]
Got it. Thanks!
