### ISSUE TITLE
Target regions without extension

### ISSUE THREAD

**Issue by sudhirthakurela** [jokergoo/EnrichedHeatmap#11]
Hi,

I am trying to create a normalized matrix without doing any extension for the target regions. My target regions are of different length. I followed as it is given in the example. 

`mat1<-normalizeToMatrix(K9me3, knownK9me3, value_column="coverage", extend = 0,  mean_mode="w0", w=50 )`

However, this is giving me error:

Error in seq.default(s, e, by = w) : wrong sign in 'by' argument

I can create a matrix if I give some value for extension, but not with extend=0

Could you please let me know why?

Sudhir

**Comment by jokergoo** [comment]
Hi,

Which version of the package are you using? If possible, can you send me `K9me3` and `knownK9me3` so that I can check it locally? My email address is `jokergoo at gmail dot com`. Thanks!
