### ISSUE TITLE
`getSignalsFromList` fails.

### ISSUE THREAD

**Issue by sameet** [jokergoo/EnrichedHeatmap#15]
Hi,

I did the following:
    
  
    l1.tss <- NULL
    for(i in seq_along(l1.gr){
        l1.tss[[i]] <- normalizeToMatrix(l1.gr[[i]], cpg.obj$CpGi, value_column="meth", mean_mode = "absolute",  extend = 1000, w = 50, empty_value = NA, smooth = T, target_ratio=0.3)
    }
    l1.mat <- getSignalsFromList(l1.tss)
    Error in attr(l1.tss[[1]], as.list("upstream_index", "target_index")) :
        exactly one attribute 'which' must be given
   

Any advice is appreciated.

**Comment by jokergoo** [comment]
I am sorry that I just found I missed this issue. Do you still have this problem?

**Comment by sameet** [comment]
Yes.

**Comment by jokergoo** [comment]
I think you should initialize `l1.tss` as `l1.tss <- list()`.

**Comment by igordot** [comment]
I am actually getting the same error.
```
> mat_list = list()
> for(i in seq_along(bw_list)) {
+   mat_list[[i]] = normalizeToMatrix(bw_list[[i]], tss_subset, value_column = "score")
+ }
> mat_mean = getSignalsFromList(mat_list)
Error in attr(lt[[i]], c("upstream_index", "target_index", "downstream_index",  : 
  exactly one attribute 'which' must be given
```

**Comment by jokergoo** [comment]
Hi, I think I have fixed this bug. Can you update the package?

```
library(devtools)
install_github("jokergoo/EnrichedHeatmap")
```
