### ISSUE TITLE
Adding rowname to enrichedHeatmap

### ISSUE THREAD

**Issue by LucoLab** [jokergoo/EnrichedHeatmap#17]
Hi,

I have two Grange objects : 
```
GRanges object with 3 ranges and 1 metadata column:
          seqnames                 ranges strand |     score
             <Rle>              <IRanges>  <Rle> | <numeric>
    APBB3     chr5 [140562659, 140562659]      * |   81.4911
  APBB3.1     chr5 [140562660, 140562665]      * |   39.7189
  APBB3.2     chr5 [140562666, 140562666]      * |    60.605
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
GRanges object with 3 ranges and 2 metadata columns:
          seqnames                 ranges strand |        name     score
             <Rle>              <IRanges>  <Rle> | <character> <numeric>
    APBB3     chr5 [140562664, 140562664]      - | 0.201_APBB3         0
  APBB3.1     chr5 [140562664, 140562664]      - | 0.201_APBB3         0
  APBB3.2     chr5 [140562664, 140562664]      - | 0.201_APBB3         0

mat12 = normalizeToMatrix(gr_exons, gr_exon_list_start, value_column = "score", extend = c(opt$upstream, opt$downstream), mean_mode = "w0", w = 1)

png(file=paste0(c(dirname(opt$file),"final.png"),collapse="/"),width = 500,height=700)
EnrichedHeatmap(mat12, name = "H3K4me3", show_row_names = TRUE, width = unit(5, "mm"))
dev.off()

```
I got the following error...I'd like to have rownames added on the left of the enriched heatmap. What is going on here ?  Thanks 

`Error in Heatmap(mat, row_order = od, cluster_columns = FALSE, cluster_rows = cluster_rows,  :    formal argument "show_row_names" matched by multiple actual arguments Calls: EnrichedHeatmap -> Heatmap`

**Comment by jokergoo** [comment]
Hi, in the old version of this package, `show_row_names` is enforced to be `FALSE`. I have updated the package and now you can set `show_row_names = TRUE` in the function.

Please update the package by:

```
devtools::install_github("jokergoo/EnrichedHeatmap")
```

**Comment by LucoLab** [comment]
Yeah thanks, I 'll give a try.
I saw after in the doc that is was enforced...sorry
It's a really impressive and useful work you have done here. congrats !
I'm just beginning to work with this package so maybe other questions will come later :)

**Comment by LucoLab** [comment]
Hey, I think there is bug plotting different stranded coordinates. Could you hilight me on that ?
I want to plot around a position.

**POS STRAND plot final_pos.png**

> GRanges object with 2 ranges and 1 metadata column:
>       seqnames                 ranges strand |     score
>          <Rle>              <IRanges>  <Rle> | <numeric>
>   [1]     chr5 [140562658, 140562659]      * |   81.4911
>   [2]     chr5 [140562660, 140562665]      * |   39.7189

>   seqinfo: 1 sequence from an unspecified genome; no seqlengths
> GRanges object with 1 range and 2 metadata columns:
>       seqnames                 ranges strand |        name     score
>          <Rle>              <IRanges>  <Rle> | <character> <numeric>
>   [1]     chr5 [140562664, 140562663]      + | 0.201_APBB3         0

![final_pos](https://user-images.githubusercontent.com/27011715/29565464-53e2a824-8746-11e7-8d30-9b897ac418c5.png)

**NEG STRAND plot final_neg.png**

> GRanges object with 2 ranges and 1 metadata column:
>       seqnames                 ranges strand |     score
>          <Rle>              <IRanges>  <Rle> | <numeric>
>   [1]     chr5 [140562658, 140562659]      * |   81.4911
>   [2]     chr5 [140562660, 140562665]      * |   39.7189

>   seqinfo: 1 sequence from an unspecified genome; no seqlengths
> GRanges object with 1 range and 2 metadata columns:
>       seqnames                 ranges strand |        name     score
>          <Rle>              <IRanges>  <Rle> | <character> <numeric>
>   [1]     chr5 [140562664, 140562663]      - | 0.201_APBB3         0

![final_neg](https://user-images.githubusercontent.com/27011715/29565463-53d742b8-8746-11e7-94fc-6c5ad0ae46df.png)

Neg strand plot seems incorect, the dotted line should be shifted from one to the right.

If I want to correct that I need to shift position minus 1. That's weird , no ?

**NEG STRAND plot final_neg_correct.png**

> GRanges object with 2 ranges and 1 metadata column:
>       seqnames                 ranges strand |     score
>          <Rle>              <IRanges>  <Rle> | <numeric>
>   [1]     chr5 [140562658, 140562659]      * |   81.4911
>   [2]     chr5 [140562660, 140562665]      * |   39.7189
> 
> 
>   seqinfo: 1 sequence from an unspecified genome; no seqlengths
> GRanges object with 1 range and 2 metadata columns:
>       seqnames                 ranges strand |        name     score
>          <Rle>              <IRanges>  <Rle> | <character> <numeric>
>   [1]     chr5 [140562663, 140562662]      - | 0.201_APBB3         0

![final_neg_correct](https://user-images.githubusercontent.com/27011715/29565700-4b4c1ed8-8747-11e7-9401-6cf06fc9a61b.png)

I plot as follows ( gr_exons, gr_exon_list_start are the Grange object printed before) 

```
mat12 = normalizeToMatrix(gr_exons, gr_exon_list_start, value_column = "score", extend = c(15,15) , mean_mode = "absolute", w = 1)

png(file=paste0(c(dirname(opt$file),"final.png"),collapse="/"),width = 500,height=700)
EnrichedHeatmap(mat12, name = "exons",rect_gp = gpar(col= "white"),show_row_names = TRUE,row_names_side = "left",width = unit(5, "cm"),top_annotation = HeatmapAnnotation(lines = anno_enriched()), top_annotation_height = unit(2, "cm")) +
Heatmap(dpsi, col = c("white", "orange"), name = "dpsi", show_row_names = TRUE, width = unit(10, "mm"))
```

**Comment by ZheFrenchKitchen** [comment]
In the last version, you can set

>  show_row_names = TRUE

 in the function for enrichedheatmap.
But when you have a lot of values (~200) it's ugly, do you have a trick to increase visibility for the rownames ?I tried to change fontsize in row_names_gp  and to plot a higher picture but that was not crazy.

**Comment by jokergoo** [comment]
@LucoLab sorry for the late reply, I was on summer vocation last several weeks.

And thanks for reporting this bug! that is something I didn't test because in my ordinary analysis, I never need to set window size of 1bp, thus it is very easy for me to miss this 1bp shift. I will look deep into the code and let you known as soon as I fix it.

**Comment by jokergoo** [comment]
@ZheFrenchKitchen basically I think if you have many genes, it is not a good idea to plot all gene names, even if you reduce the font size, the plot will still look ugly. One solution is to only plot a subset of genes of interest and you can use `anno_link()` to arrange the labels to let them do not overlap to each other if they are too close:

http://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s4.heatmap_annotation.html#toc_14
