### ISSUE TITLE
SUGGESTION: More efficient code using matrixStats (>= 0.50.0)

### ISSUE THREAD

**Issue by HenrikBengtsson** [jokergoo/EnrichedHeatmap#2]
In [matrixStats (>= 0.50.0)](https://cran.r-project.org/package=matrixStats), which is now on CRAN, we introduce support for subsetted calculations that are [optimized both for speed and memory usage](http://www.jottr.org/2015/12/matrixstats-subsetted-calculations.html).  There are now new arguments `idxs`, `rows` and `cols` for most functions which allow you to very easily make use of this.

For your package, I believe the following functions could gain from this:
```r
$EnrichedHeatmap$anno_enriched
colSds(mat[i, , drop = FALSE])
```
by updating to something like:
```r
$EnrichedHeatmap$anno_enriched
colSds(mat, rows=i)
```
and adding `matrixStats (>= 0.50.0)` to your `DESCRIPTION` file.

**Comment by jokergoo** [comment]
I also saw the update of matrixStats on Rbloggers. I will definitely update my package as well as my other projects. Thanks!
