### ISSUE TITLE
row order when plotting multiple heatmap

### ISSUE THREAD

**Issue by olechnwin** [jokergoo/EnrichedHeatmap#20]
I may be wrong? But, I noticed when doing multiple heatmap like in the example that plot H3K4me3, methylation and log2(rpkm+1), if you didn't specify row_order in each heatmap calls (Heatmap and EnrichedHeatmap), the row order in each of this multiple heatmaps is not the same. (i.e. it doesn't plot the same region across heatmap and therefore the rpkm is also not the correct genes) ?
Did I miss something? Thanks.

**Comment by sameet** [comment]
Also Supplementary File link is not working. I did not see that file in the Vignettes folder.

**Comment by jokergoo** [comment]
@olechnwin The row orders of all heatmaps are always the same. You can see following examples:

```
EnrichedHeatmap(mat1[1:20, ], col = col_fun, name = "H3K4me3", show_row_names = TRUE) +
EnrichedHeatmap(mat2[1:20, ], col = meth_col_fun, name = "methylation", show_row_names = TRUE) +
Heatmap(log2(rpkm+1)[1:20], col = c("white", "orange"), name = "log2(rpkm+1)",
    width = unit(5, "mm"))
```

![image](https://user-images.githubusercontent.com/449218/31815678-aab8f796-b58d-11e7-883a-8dcfaeacc6c4.png)

If you have something strange, can you attach the code also?

**Comment by jokergoo** [comment]
@sameet which file is not working? Which file in the vignette folder?

**Comment by olechnwin** [comment]
@jokergoo, sorry. I just saw your reply. I figured I need to specify the row_order and did not pay attention to this thread anymore.
In the version that I am using (1.4.0), show_row_names=TRUE generates this error:

`Error in Heatmap(mat, row_order = od, cluster_columns = FALSE, cluster_rows = cluster_rows,  : 
  formal argument "show_row_names" matched by multiple actual arguments
`

Since I cannot verify using show_row_names, I did the following:

`hm5 = EnrichedHeatmap(mat5, name = "",show_heatmap_legend=FALSE,col=col_fun)
row_order_list = row_order(draw(hm5))`

which shows different row_order_list for different heatmap. 
I think this is because they are not connected by the '+' sign (I assumed?)
So, if multiple heatmaps are connected by the '+' sign, they should have the same rows?
Is the show_row_names only works in certain version? Thanks!

**Comment by jokergoo** [comment]
Hi,


I think you are still using the old version which does not support `show_row_names`. You can update the packages by:


library(devtools)

install_github("jokergoo/ComplexHeatmap")

install_github("jokergoo/EnrichedHeatmap")


And what do you mean by "which shows different row_order_list for different heatmap?"? Can you give me an example?

When there are multiple heatmaps, they have the same row order.


?


________________________________

**Comment by olechnwin** [comment]
Hi Jokergoo,

I meant if I do the following:
```
hm5 = EnrichedHeatmap(mat5, name = "",show_heatmap_legend=FALSE,col=col_fun) 
row_order_list5 = row_order(draw(hm5)) 
hm6 = EnrichedHeatmap(mat6, name = "",show_heatmap_legend=FALSE,col=col_fun) 
row_order_list6 = row_order(draw(hm6)) 
```
row_order_list5 and row_order_list6 are not the same.

And so I am wondering if I draw both heatmap like follows:

`draw(hm5+hm6)`

Then in this case, the order will be the same?

I cannot find my previous code where I thought the orders were not the same when I do 'draw(hm5+hm6). It is difficult to figure out without the show_row_name. I'll post if I find them.

**Comment by jokergoo** [comment]
Yes, because mat5 and mat6 are different, the order of hm5 and hm6 is also different. But if you put as hm5 + hm6, the row ordering

is only applied to the first numeric matrix or a matrix you specified as the main heatmap.?


________________________________

**Comment by olechnwin** [comment]
Hi @jokergoo 

I'm trying to print the row names like your example [above](https://github.com/jokergoo/EnrichedHeatmap/issues/20#issuecomment-338162344) but it will only print one row names. How do I display both row names?
I am now using EnrichedHeatmap version 1.16 and these are the codes I ran:
```
set.seed(123)
load(system.file("extdata", "chr21_test_data.RData", package = "EnrichedHeatmap"))
tss = promoters(genes, upstream = 0, downstream = 1)
mat1 = normalizeToMatrix(H3K4me3, tss, value_column = "coverage", 
 extend = 5000, mean_mode = "w0", w = 50)
mat2 = normalizeToMatrix(meth, tss, value_column = "meth", mean_mode = "absolute",
 extend = 5000, w = 50, background = NA, smooth = TRUE)
EnrichedHeatmap(mat1[1:20,], name = "H3K4me3",show_row_names = TRUE,
 top_annotation = HeatmapAnnotation(enrich = anno_enriched(axis_param = list(side = "left")))) + 
 EnrichedHeatmap(mat2[1:20,], name = "methylation",show_row_names=TRUE)
```
![image](https://user-images.githubusercontent.com/20069067/92270511-304b8100-eeb4-11ea-9b48-39c33f5ff25a.png)

Thank you!

**Comment by olechnwin** [comment]
I just wanted to make sure I didn't make stupid mistakes and was wondering since you were able to do that. Is it now not possible to draw the row names for both matrix? Just curious.

**Comment by jokergoo** [comment]
Then you can do:

```r
ht_list = EnrichedHeatmap(...) + EnrichedHeatmap(...)
draw(ht_list, auto_adjust = FALSE)
```

**Comment by olechnwin** [comment]
Great! Nice to know. Thank you very much.
