### ISSUE TITLE
missing a line in the line graph on top of the heatmap

### ISSUE THREAD

**Issue by lifengJGI** [jokergoo/EnrichedHeatmap#22]
There is a line missing (black line of the cluster one) in the line graph. Any solutions? The cluster setting is same for histone marks and DNA methylation. Thanks

<img width="1480" alt="screen shot 2018-02-21 at 3 53 03 pm" src="https://user-images.githubusercontent.com/13069533/36512484-6cde018e-171f-11e8-8088-dbe736a59fe3.png">

**Comment by jokergoo** [comment]
OK, can you also attach the code?

**Comment by lifengJGI** [comment]
Here is the code. Thanks.
[DNA_methylation_histone_modification_plot_Tx.R.txt](https://github.com/jokergoo/EnrichedHeatmap/files/1748867/DNA_methylation_histone_modification_plot_Tx.R.txt)

**Comment by jokergoo** [comment]
In the part where you make methylation heatmap, the setting for color is wrong:

gp = gpar(col = 2:6, ...

it should be 

gp = gpar(col = 1:6,

**Comment by lifengJGI** [comment]
oh yes, thanks for pointing the error.
