### ISSUE TITLE
Give an example for calculating correlation of binding and expression.

### ISSUE THREAD

**Issue by sameet** [jokergoo/EnrichedHeatmap#23]
First off, thank you for creating this package. Can you give a step-by-step instruction set for generating correlation plots for gene-expression and protein binding or methylation status and gene-expression?

Best,
Sameet

**Comment by jokergoo** [comment]
You can find the general description of the method in following link:

http://www.bioconductor.org/packages/devel/bioc/vignettes/EnrichedHeatmap/inst/doc/roadmap.html#toc_2
