### ISSUE TITLE
factor ordering for discrete values

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/EnrichedHeatmap#27]
Hi,

Thanks for the new tutorial http://bioconductor.org/packages/release/bioc/vignettes/EnrichedHeatmap/inst/doc/visualize_categorical_signals_wrapper.html

I have a question on the numeric representation of the discrete values. For chromHMM downloaded from epigenome Roadmap, the state is coded as E1..E15

```
> test_f1<- factor(paste0("E", 1:15), levels =paste0("E", 1:15))
> test_f2<- factor(paste0("E", 1:15))
> test_f1
 [1] E1  E2  E3  E4  E5  E6  E7  E8  E9  E10 E11 E12 E13 E14 E15
Levels: E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14 E15
> test_f2
 [1] E1  E2  E3  E4  E5  E6  E7  E8  E9  E10 E11 E12 E13 E14 E15
Levels: E1 E10 E11 E12 E13 E14 E15 E2 E3 E4 E5 E6 E7 E8 E9
> as.numeric(test_f1)
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15
> as.numeric(test_f2)
 [1]  1  8  9 10 11 12 13 14 15  2  3  4  5  6  7

```
If I set  `levels =paste0("E", 1:15)`, the final matrix will have 1 represent E1, 2 represent E2... right?

Also the final mat has the same row order as the `tss` right? 

Thanks!
Tommy

**Comment by jokergoo** [comment]
Yes!

**Comment by crazyhottommy** [comment]
thanks!
