### ISSUE TITLE
Suggestion: gpar() for heatmap border

### ISSUE THREAD

**Issue by lakhanp1** [jokergoo/EnrichedHeatmap#31]
Hi Zuguang,

Thank you for creating and actively maintaining `ComplexHeatmap` and `EnrichedHeatmap` packages.

`EnrichedHeatmap` provides a logical option `border` to show or hide the plot border. Is it possible to provide an option to control the graphic parameters of the plot border?

Thank you again!
Lakhan

**Comment by jokergoo** [comment]
Hi Lakhan,

I am currently developing a new version ComplexHeatmap package and I will update EnrichedHeatmap package accordingly. In the new version, I will add this functionality.

Currently, you can implement it by decorate_heatmap_body()

```{r}
draw(EnrichedHeatmap(..., border = FALSE))
decorate_heatmap_body(..., {
    grid.rect(gp = gpar(...))  # control the border here
})
```

**Comment by lakhanp1** [comment]
Thank you Zuguang. I am looking forward to the new version of ComplexHeatmap.
