### ISSUE TITLE
Position line color not uniform for top annotation and main heatmap body

### ISSUE THREAD

**Issue by lakhanp1** [jokergoo/EnrichedHeatmap#34]
Hi Zuguang,

I am using the latest updated EnrichedHeatmap package (v1.13.1) from GitHub. I wanted to change position line color using `pos_line_gp` option. I noticed that when I change the color in gpar() argument, the line color is not changed for top annotation. The color is reflected correctly for main heatmap body whereas the top annotation position line is still in default `black` color. Please refer below for the reproducible example.
```
library(EnrichedHeatmap)

set.seed(123)
load(system.file("extdata", "chr21_test_data.RData", package = "EnrichedHeatmap"))

tss = promoters(genes, upstream = 0, downstream = 1)

mat1 = normalizeToMatrix(H3K4me3, tss, value_column = "coverage", 
                         extend = 5000, mean_mode = "w0", w = 50)


col_fun = circlize::colorRamp2(quantile(mat1, c(0, 0.99)), c("white", "red"))

## color of the position line is different for annotation and heatmap body
EnrichedHeatmap(
  mat1, col = col_fun, name = "H3K4me3", row_km = 3,
  top_annotation = HeatmapAnnotation(
    enriched = anno_enriched(
      gp = gpar(col = 2:4, lty = 1:3)),
    annotation_height = unit(4, "cm")
  ),
  column_title = "Enrichment of H3K4me3", row_title_rot = 0,
  pos_line_gp = gpar(lty = 2, col = "#F4A460", lwd = 1))
```

![rplot](https://user-images.githubusercontent.com/8170335/48993130-d06c6600-f176-11e8-838f-c79d12088960.png)

Thank you!
~Lakhan.

**Comment by jokergoo** [comment]
Actually you need to manually set `pos_line` and `pos_line_gp` in `anno_enriched()` as well. 

But thanks to your comment, now by default `pos_line` and `pos_line_gp` in `anno_enriched()` will take the same value in `EnrichedHeatmap()` that if you try your code again, the vertical line in the annotation will be orange.

**Comment by jokergoo** [comment]
If you also update ComplexHeatmap package, you can find the order of k-kmeans slices now are nicely set.

![image](https://user-images.githubusercontent.com/449218/49021974-1b48a680-f194-11e8-834b-5b356612b675.png)

**Comment by lakhanp1** [comment]
Thank you Zuguang.
Yes, I updated to latest ComplexHeatmap and the new features are really good.
