### ISSUE TITLE
Colors of the top_annotation switch randomly

### ISSUE THREAD

**Issue by jdekanter** [jokergoo/EnrichedHeatmap#35]
Dear Zuguang,

I am working with the EnrichedHeatmap package. I think it is great, thank you for creating and maintaining it!

I am having trouble with the color assignment of the top-annotation lines, when partitioning the data.
I am doing something similar to this example from the vignette.

```{r}
_partition = paste0("cluster", kmeans(mat1, centers = 3)$cluster)
lgd = Legend(at = c("cluster1", "cluster2", "cluster3"), title = "Clusters", 
    type = "lines", legend_gp = gpar(col = 2:4))
ht_list = Heatmap(partition, col = structure(2:4, names = paste0("cluster", 1:3)), name = "partition",
              show_row_names = FALSE, width = unit(3, "mm")) +
          EnrichedHeatmap(mat1, col = col_fun, name = "H3K4me3",
              top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = 2:4),
                yaxis_facing = "left")), 
              column_title = "H3K4me3") + 
          EnrichedHeatmap(mat2, col = meth_col_fun, name = "methylation",
              top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = 2:4))), 
              column_title = "Methylation") +
          Heatmap(log2(rpkm+1), col = c("white", "orange"), name = "log2(rpkm+1)", 
              show_row_names = FALSE, width = unit(5, "mm"))
draw(ht_list, split = partition, annotation_legend_list = list(lgd))_
```

This main difference is that I want to use custom colors (instead of 2:4), and I want to each color to a specific "cluster" (partitioning group). 
Following the code above, I can assign my colors to names for the Legend via:
     Legend(at =  paste0("cluster", c(3,2,1)), ....) and for the Heatmap via
     Heatmap(..., col = structure(2:4, names = paste0("cluster", c(3,2,1)), ...),
but for the EnrichedHeatmap, I don't understand how to do this.
I your example you only do:
     EnrichedHeatmap(..., top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = 2:4)),
but applying this code on my own data with custom colors, the colors for all my datasets switch for the lines in the top-annotation, while the colors created by Legend and Heatmap stay correct: 
![image](https://user-images.githubusercontent.com/33459230/50778944-68458f80-129f-11e9-83ba-e5788b9c0331.png)
(In the top-annotation of the first column, the colors clearly don't match with the legend).
First, I thought they were assigned in alphabetical order, then that they were assigned based on the order of _unique(partition)_, but both are not the case. 

So my question: How can I in the code above explicitly link a color to a name.
My (failed) attempts were:

```
_colors <- gpar(col = c('blue', 'green', 'red'), names =paste0('cluster', c(3,1,2))
EnrichedHeatmap(..., top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = colors)), ...)_
```

and:

```
_colors <- gpar(col = c('blue', 'green', 'red'))
names(colors$col) <- paste0('cluster', c(3,1,2)
EnrichedHeatmap(..., top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = colors)), ...)_
```

Thank you in advance for your time!

**Comment by jokergoo** [comment]
```
colors <- gpar(col = c('blue', 'green', 'red'), names =paste0('cluster', c(3,1,2))
```
and
```
colors <- gpar(col = c('blue', 'green', 'red'))
names(colors$col) <- paste0('cluster', c(3,1,2)
```

both are wrong.  Since `colors` is only set like `gp = gpar(col = colors)`, the value should only be a simple vector with no names, like (c("red", "blue", ...)`).

In following code:

```
EnrichedHeatmap(..., top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = 2:4))
```
The order of the color set in `gpar(col = ...)` always correspond to the order of row-slices from top to bottom. E.g. if `gpar(col = 2:4)`, it means the top row-slice is red, the middle is green and the third is  blue, while if `gpar(col = c(2, 4, 3)`, the middle becomes blue and the bottom becomes green. So according to your plot, the color should be set as `c("blue", "orange", "red", "green")`.

**Comment by jdekanter** [comment]
Sorry forgot to close the issue. Thank you for your answer
