### ISSUE TITLE
multiplemEnrichedheatmaps with only line plots

### ISSUE THREAD

**Issue by Papareddy** [jokergoo/EnrichedHeatmap#36]
Hello,

I am trying to plot methylation value in differnt tissue types on gene bodies. I normally use deeptools plotProfile function but it doesn't have a smoothening option. So I like Enrichedheatmap for that reason. However I was wondering whether i can plot only the lineplot with out heatmap.

Hope i am making sense.
Many thanks,
Ranj
![enrichedheatmap_lineplot](https://user-images.githubusercontent.com/33577042/52964431-8fb17100-33a2-11e9-9acd-70fc92f2cb16.png)

**Comment by jokergoo** [comment]
Hi, there are two ways:

1. you can refer to the plot __above__ the section: http://bioconductor.org/packages/devel/bioc/vignettes/EnrichedHeatmap/inst/doc/roadmap.html#toc_7 where you can use `add_anno_enriched()` to extract the plot which is exactly the same as on top of the heatmap.

2. Directly plot `colMeans(m)` where `m` is the normalized matrix from `normalizeToMatrix()`. The disadvantage is if you split `m` in the heatmap, you need to manually split `m` into `m1` and `m2`, later add lines for `colMeans(m1)` and `colMeans(m2)`.
