### ISSUE TITLE
customer reference genes annotation

### ISSUE THREAD

**Issue by skytguuu** [jokergoo/EnrichedHeatmap#37]
Hi,

I tried to use enrichment heatmap to normalize chip-seq data. However, when I loaded my reference gene annotation (gtf file) downloaded from UCSC, then it repored an error.
###################
the command is:
normalizeToMatrix(k4me3,tss,value_column="Peak")
##################
the error is: 
Error in (function (classes, fdef, mtable): unable to find an inherited method for function 'strand<-' for signature '"data.frame","character"'.

Could you give me some advises?
Thanks for your help.
Best,
Garen

**Comment by jokergoo** [comment]
Can you show me the first several lines of `k4me3` and `tss`?

**Comment by skytguuu** [comment]
Thanks for your promptly help. My first lines of k4me3 and tss are as followed:
##########
> tss[1:2]
GRanges object with 2 ranges and 2 metadata columns:
      seqnames             ranges strand |     tx_id     tx_name
         <Rle>          <IRanges>  <Rle> | <integer> <character>
  [1]     chr1 [4797974, 4797974]      + |         1  uc007afg.1
  [2]     chr1 [4797974, 4797974]      + |         2  uc007afh.1
  -------
  seqinfo: 35 sequences (1 circular) from mm9 genome
> k4me3[1:2]
GRanges object with 2 ranges and 2 metadata columns:
        seqnames             ranges strand |     score      peak
           <Rle>          <IRanges>  <Rle> | <integer> <integer>
  X0001     chr1 [4774089, 4776789]      * |      1815      1288
  X0002     chr1 [4797273, 4799175]      * |      1455       378
  -------
  seqinfo: 15 sequences from an unspecified genome; no seqlengths
############
And now, I solved this problem because I did not use "toGRanges" to change the k4me3 input format. But now I am confused about the parameter of "value_column". Because I got the output from macs2, it is the narrowpeak file. Those columns are including "score" and "Peak". I was wondering which one (score or peak) is better to use to normalization?

Thanks

**Comment by jokergoo** [comment]
I normally use the fifth column in the bed file for the "narrowPeak" file because it is used for genomic track visualization and I assume they are kind like normalized values.

**Comment by skytguuu** [comment]
I am appreciated for your help.

Thanks,
Best
