### ISSUE TITLE
Mixed colors in top_annotations

### ISSUE THREAD

**Issue by CharlesJB** [jokergoo/EnrichedHeatmap#38]
Hello,

I'm having a problem where the colors on the top annotation is not matching the partition colors when I add an extra heatmap.

It is similar to [Issue #35](https://github.com/jokergoo/EnrichedHeatmap/issues/35), except that the problem does not seem to have the same cause as I'm using a simple character vector for the colors.

What is confusing me is that producing two heatmaps with almost identical code is giving me different results:

![Imgur](https://i.imgur.com/Ln383XJ.png)

The one on the left is produced with this command:

```r
draw(eh + hp, split = partitions)
```

The one on the right is produced with this command:

```r
draw(ht_logfc + eh + hp, split = partitions)
```

In both case, the colors of the partition are what I expected, but in the second heatmap the colors are not matching in the top annotation. 

Here is the complete code I used to produce this example:

```r
library(EnrichedHeatmap)
library(circlize)
library(ggthemes)
library(magrittr)

load("test.RData")

set.seed(99841)
col_blind <- colorblind_pal()(length(unique(partitions)))

m <- normalizeToMatrix(test_cov, peaks, value_column = "score",
                       extend = 5000, mean_mode = "w0",w = 100)

ha <- HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = col_blind),
                        axis_param = list(facing = "inside")))

eh <- EnrichedHeatmap(m, name = "test", column_title = "test",
                      top_annotation = ha)

ht_logfc <- Heatmap(logfc, name = "Fold Change", show_row_dend = FALSE,
                    width = unit(1, "cm"))

hp <- Heatmap(partitions, col = structure(col_blind), name = "",
              show_row_names = FALSE, width = grid::unit(3, "mm"))

draw(eh + hp, split = partitions)
draw(ht_logfc + eh + hp, split = partitions)
```

The `test.RData` file can be downloaded from:

* https://www.dropbox.com/s/ti473ii39m1m0gc/test.RData?dl=0

I'm probably missing something obvious, but I can't find it.

Thank you very much for the help!
Charles.

Here is my sessionInfo:

```r
R version 3.6.0 beta (2019-04-16 r76403)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
 [1] parallel  stats4    grid      stats     graphics  grDevices utils
 [8] datasets  methods   base

other attached packages:
 [1] magrittr_1.5           ggthemes_4.2.0         circlize_0.4.6
 [4] EnrichedHeatmap_1.14.0 GenomicRanges_1.36.0   GenomeInfoDb_1.20.0
 [7] IRanges_2.18.1         S4Vectors_0.22.0       BiocGenerics_0.30.0
 [10] ComplexHeatmap_2.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1             compiler_3.6.0         pillar_1.4.1
 [4] RColorBrewer_1.1-2     XVector_0.24.0         tools_3.6.0
 [7] bitops_1.0-6           zlibbioc_1.30.0        tibble_2.1.3
 [10] gtable_0.3.0           lattice_0.20-38        clue_0.3-57
 [13] pkgconfig_2.0.2        png_0.1-7              rlang_0.3.4
 [16] GenomeInfoDbData_1.2.1 stringr_1.4.0          dplyr_0.8.1
 [19] cluster_2.1.0          GlobalOptions_0.1.0    tidyselect_0.2.5
 [22] locfit_1.5-9.1         glue_1.3.1             R6_2.4.0
 [25] GetoptLong_0.1.7       purrr_0.3.2            ggplot2_3.2.0
 [28] scales_1.0.0           matrixStats_0.54.0     assertthat_0.2.1
 [31] shape_1.4.4            colorspace_1.4-1       stringi_1.4.3
 [34] RCurl_1.95-4.12        lazyeval_0.2.2         munsell_0.5.0
 [37] crayon_1.3.4           rjson_0.2.20
```

**Comment by jokergoo** [comment]
Try:

```r
draw(eh + hp, split = partitions, main_heatmap = "test")
draw(ht_logfc + eh + hp, split = partitions, main_heatmap = "test")
```

Without specifying `main_heatmap`, row orders of all heatmaps are determined by the first numeric heatmap.

**Comment by CharlesJB** [comment]
It's working to correct the color of the top annotation when I add the `main_heatmap = "test"` parameter (i.e.: The topmost line is gold, the second one is black and the last one is blue), but I would like to keep the ordering based on the fold change heatmap.

The heatmap section of the 2nd example is what I am expecting. It's the top annotation that should be identical to the 1st heatmap based on the signal strength in each partition:

![Imgur](https://i.imgur.com/PQbyghW.png)

Thank you very much for your help!

**Comment by CharlesJB** [comment]
Do you think it could be a bug or am I missing something?

**Comment by jokergoo** [comment]
Hi, here the colors (`col = col_blind`) defined in 

```r
ha <- HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = col_blind),
                        axis_param = list(facing = "inside")))
```
The order of the colors will not be automatically adjusted according to how row clusters are arranged.
In other words, the first color in `col_blind` (which is black) always corresponds to the first row clusters (which has low signal in the center).

In following two heatmaps:

![](https://camo.githubusercontent.com/839727da2030536682bcfede7418f9a935802091/68747470733a2f2f692e696d6775722e636f6d2f4c6e333833584a2e706e67)

You can see in the left one, the first row-cluster has intermediate signal, which represents in the top annotation as the black line between the brown and blue lines. And in the right heatmap, the first row--cluster has the lowest signal, which represents as the black line which is the lowest in the top annotation.

The colors of lines in the top annotation have no relation to the colors of the "partition" row annotation.
You need to adjust the line colors manually.

**Comment by CharlesJB** [comment]
Thank you for your explanation.

If I understand correctly, the heatmap is first clustered, then it will be splitted based on the order that the partitions values are found from top to bottom.

Is there a way to force the order of the splitted section of the heatmap? Would it be possible to have the CHD4 section at the top in the 2nd heatmap while keeping the ordering based on the fold changes for each section?

**Comment by CharlesJB** [comment]
Or would it be possible to for a color to be associated with a specific value from the partition? Like in the example, is there a way to force the partition with the "Gfi1" value from the `partitions` vector to be blue?

In other words, is it possible to know which color will be used for the partition section of the heatmap before the actual clustering of the matrices?

In my example, there is a very obvious difference between each section of the heatmap that allows me to see that the colors are not matching in the partition section compared to the top annotation. But if the difference was more subtle, I could miss it and keep incorrect colors.

My main goal here is to see which curve from the top annotation corresponds to which section of the splitted heatmap. The partition section of the heatmap seemed the most straightforward approach, but maybe there is an alternative?

**Comment by jokergoo** [comment]
The order of row-clusters can be controlled by setting the splitting variable `partitions` as a factor where the levels of the factor controls the order of row-clusters:

```r
# note the ordering is from top to bottom
partition = factor(partition, levels = c("CDH4", "CHD4/Gfi1", "Cfi4"))
```

**Comment by CharlesJB** [comment]
Sorry for the delay, I was away for the last weeks.

I tried using factors as you said but it did not influence the ordering of the row-clusters:

```
library(EnrichedHeatmap)
library(circlize)
library(ggthemes)
library(magrittr)

load("test.RData")
partitions <- factor(partitions, levels = c("CHD4", "CHD4/Gfi1", "Gfi1"))

set.seed(99841)
col_blind <- colorblind_pal()(length(unique(partitions)))

m <- normalizeToMatrix(test_cov, peaks, value_column = "score",
                       extend = 5000, mean_mode = "w0",w = 100)

ha <- HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = col_blind),
                        axis_param = list(facing = "inside")))

eh <- EnrichedHeatmap(m, name = "test", column_title = "test",
                      top_annotation = ha)

ht_logfc <- Heatmap(logfc, name = "Fold Change", show_row_dend = FALSE,
                    width = unit(1, "cm"))

hp <- Heatmap(partitions, col = structure(col_blind), name = "",
              show_row_names = FALSE, width = grid::unit(3, "mm"))

draw(ht_logfc + eh + hp, split = partitions)
```

![Imgur](https://i.imgur.com/0fh9xuV.png)

**Comment by jokergoo** [comment]
Sorry for the late reply. I was on vocation.

In your code, the first heatmap which is the log2fold change heatmap controls the row clustering and ordering. Rows are clustered and the three row-slices are also clustered. To make the row slice order exact as `c("CHD4", "CHD4/Gfi1", "Gfi1")`,  you need to turn off the clustering on the row slices:

```r
ht_logfc <- Heatmap(logfc, name = "Fold Change", show_row_dend = FALSE,
                   cluster_row_slices = FALSE,
                    width = unit(1, "cm"))
```

If you update the package from GitHub, you can also specify `cluster_row_slices` in `draw()` function which directly controls the corresponding argument for the main heatmap.

```r
draw(ht_logfc + eh + hp, split = partitions, cluster_row_slices = FALSE)
```

**Comment by CharlesJB** [comment]
Yes, it does correct the problem. I did not realize there was also a clustering on the row_slices. Thank you for your answers.

Cheers!
