### ISSUE TITLE
Meaning of rows on heatmap

### ISSUE THREAD

**Issue by AYYYang** [jokergoo/EnrichedHeatmap#39]
Hi these might be naive questions:
What does each row mean on the heatmap? I assume it is each individual gene? Since they are ordered by enrichment level, I assume that the heatmap is not in the order of chr1 - chrY?
When plotting multiple heatmaps for comparing distribution of chromatin states, are the rows clustered in the same way? If the rows are different genes, how should I compare the two heatmaps? 

Thank you!

**Comment by jokergoo** [comment]
Hi,

Sorry for the late reply. I was on vocation.

When you run EnrichedHeatmap package, normally you use the following code:

```r
mat = normalizeToMatrix(signal, target, ...)
EnrichedHeatmap(mat, ...)
```

Here `mat` is the matrix for the heatmap visualization, where rows in `mat` correspond to rows in `target`. If rows in `target` are genes, then you can think rows in the heatmap are genes as well. As normal heatmaps, rows can be clustered or reordered in the heatmaps, it is not necessarily chr1-chrY, but you can control it by yourself. 

When you concatenate more than one heatmaps, you need to make sure the i^th row in all heatmap corresponds to the same thing, e.g. same gene or same region. The rows in all heatmap are adjusted simultaneously according to the first heatmap.
