### ISSUE TITLE
feature request: enrichment heatmap on genebody

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/EnrichedHeatmap#4]
Hi,

other tools such as ngs.plot can plot ChIP-seq enrichment on gene body. Since every gene is with different lengths, the idea is to scale all genes to the same length (say 10kb) and then plot. Could you please share how you are going to do it? or if you can implement this in this package?

Thanks very much!
Ming

**Comment by jokergoo** [comment]
Hi Ming,

It is already supported in this package. You only need to set the gene bodies as the target regions.

In following example, the H3K36me3 marks are enriched to gene bodies as well as 1kb upstream and downstream:

```{r}
mat = normalizeToMatrix(H3K36me3, genes, upstream =1000, downstream = 1000, ...)
EnrichedHeatmap(mat)
```

In the vignette of the package (http://www.bioconductor.org/packages/devel/bioc/vignettes/EnrichedHeatmap/inst/doc/EnrichedHeatmap.html). I showed this feature with using CpG Island (regions with certain width), basically it is same as using gene bodies.

**Comment by crazyhottommy** [comment]
Thanks! I should read the vignette more carefully...

**Comment by crazyhottommy** [comment]
Hi, I was plotting H3K27ac, it works on TSS but not on genebodies

```r
library(EnrichedHeatmap)
library(rtracklayer)

# although the bigwig file is around 300Mb, after importing, the object is ~1Gb. Takes time to read
H3K27ac<- import("my_raw.bw", format="bigWig")

## let's test using a subset of TSS
hg19.refseq.db <- makeTxDbFromUCSC(genome="hg19", table="refGene")
refseq.genes<- genes(hg19.refseq.db)
tss<- resize(refseq.genes, width=1)
tss.subset<- tss[1:1000]

mat1<- normalizeToMatrix(TCGA.27.1831.H3K27ac, tss.subset, value_column = "score", extend=5000, mean_mode="w0", w=50)

## This works
EnrichedHeatmap(mat1, col= c("white","red"), name = "H3K27ac", 
                axis_name = c("-5kb", "TSS", "5kb"),
                top_annotation = HeatmapAnnotation(lines = anno_enriched()), 
                top_annotation_height = unit(2, "cm"))

# profile in the gene body, error
mat2<- normalizeToMatrix(H3K27ac, refseq.genes[1:1000], extend= 1000)
EnrichedHeatmap(mat2, col= c("white","red"), name = "H3K27ac gene body", 
                top_annotation = HeatmapAnnotation(lines = anno_enriched()), 
                top_annotation_height = unit(2, "cm"))

Error in valid.viewport(x, y, width, height, just, gp, clip, xscale, yscale,  : 
  invalid 'yscale' in viewport

> EnrichedHeatmap(mat2)
Error in colorRamp2(seq(quantile(x, 0.01), quantile(x, 0.99), length = 3),  : 
  You should have at least two distinct break values.

```

Also `target_ratio` argument is gone now.

Thanks,
Ming
