### ISSUE TITLE
Custom ticks and label position at x-axis

### ISSUE THREAD

**Issue by ATpoint** [jokergoo/EnrichedHeatmap#40]
Hey Zuguang,

is there an option to remove the ticks at the x-axis except those at the upper/lower limit and at the center position while centering the labels at these positions as shown in this manual edit below?

Thanks!
-Alex

![Screen Shot 2019-08-16 at 11 44 43](https://user-images.githubusercontent.com/21218078/63159399-c7306b80-c01b-11e9-80e6-8ae78a20a8c0.png)

**Comment by jokergoo** [comment]
Hi, sorry for the late reply. I was on vocation.

There is no open API to remove the ticks, but you directly modify the internal function:

```r
assignInNamespace("calc_minor_ticks", function(x) NULL, ns = "EnrichedHeatmap")
EnrichedHeatmap(...)
```

The positions of the first label and the last label cannot be easily modified, unfortunately.
