### ISSUE TITLE
Error in Heatmap(mat, col, row_order = row_order, cluster_columns = FALSE,  :    unused argument (top_annotation_height = top_annotation_height)

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/EnrichedHeatmap#41]
installed both EnrichedHeatmap and ComplexHeatmap from github. you may have upgraded ComplexHeatmap to not use the `top_annotation_height` argument and these two packages are out of sync?

**Comment by jokergoo** [comment]
Hi Tommy,

`EnrichedHeatmap()` does not use `top_annotation_height` explicitly. This argument is directly passed to `Heatmap()` by `...` in `EnrichedHeatmap()`. So if `Heatmap()` does not support `top_annotation_height`, using `top_anntation_height` in `EnrichedHeatmap()` will cause an error.

Can you show me the code or the error message you have?

**Comment by crazyhottommy** [comment]
Hi Zuguang. I found that I was actually using EnrichedHeatmap from Bioconductor and ComplexHeatmap from github. after installing EnrichedHeatmap from github, the error is gone.

Sorry about that.
