### ISSUE TITLE
About the "row_split" parameter？

### ISSUE THREAD

**Issue by francisfa** [jokergoo/EnrichedHeatmap#42]
When I used `EnrichedHeatmap()` function to plot a heatmap, I wanted to split two different group. So the `row_split=split` was used. It did not work. Then I found that it using `Heatmap` of `ComplexHeatmap` package. And there is a change about this parameter: row_split ----> split. So you maybe change the `README` in the future.
Thank you.

**Comment by jokergoo** [comment]
I think you might update both EnrichedHeatmap and ComplexHeatmap packages. In the new version, both functions use `row_split` argument, but setting `split` has the same effect.

**Comment by francisfa** [comment]
ok, thank you!!
