### ISSUE TITLE
output bed regions along with each window coverage/score  

### ISSUE THREAD

**Issue by itsvenu** [jokergoo/EnrichedHeatmap#43]
Hi,

Thanks for the awesome package.

I was wondering if there is a way to get a data.frame/matrix of input regions along with the coverage of each window. Basically the data underlying the heatmap of `EnrichedHeatmap`.

Something like 
```
region bin1 bin2 bin3....
chr1:1-10 1 4 3 ...
chr2:14-20 5 7 9...
```
Any leads would be appreciated. Thanks.

**Comment by jokergoo** [comment]
The matrix is generated in the step of normalizing to target regions:

```r
mat = normalizeToMatrix(signal, target)
```

Rows in `mat` correspond to rows in `target`, and columns in `mat` correspond to bins around `target`.

**Comment by itsvenu** [comment]
Thanks for the quick reply. I tried `as.data.frame(mat)`. This seems to be what I want.

Thank you :)
