### ISSUE TITLE
how can I manually cluster with EnrichedHeatMap?

### ISSUE THREAD

**Issue by Yuxinagli** [jokergoo/EnrichedHeatmap#45]
Hi Dr Gu,
I am trying to comparing ChIPseq Enrichment of  different subset of Genes which chosen based on RNAseq data. Is there anyway I can manually  cluster these genes in different clusters rather than using K-means method. 
The example presented on Bioconductor.org  'EnrichedHeatmap(mat1, col = col_fun, name = "H3K4me3", 
    row_split = sample(c("A", "B"), length(genes), replace = TRUE),
    column_title = "Enrichment of H3K4me3")  '   is based on random sampling which is not suitable for my need. 
Thanks

**Comment by jokergoo** [comment]
If you have a vector which contains the categories of genes (e.g. `gene_category`), you can assign it to the `row_split` argument:

```r
EnrichedHeatmap(..., row_split = gene_category)
```
