### ISSUE TITLE
Strange V Shape when generating heatmap?

### ISSUE THREAD

**Issue by Jome0169** [jokergoo/EnrichedHeatmap#46]
Hello, I've recently hit an issue with enriched heatmap where during generation the an ATAC-seq metaplot I get a very strange V shape at the bottom of the heatmap, and I'm unsure why this is. Attached is an image of the graphical issue. You can see the V shape I'm talking about in the "Gene" section of the plot 
[ATAC_quality.pdf](https://github.com/jokergoo/EnrichedHeatmap/files/4031392/ATAC_quality.pdf)

**Comment by Jome0169** [comment]
Hello,

I've been using EnrichedHeatmap for a few months now and have really been enjoying it. I've recently hit an issue where when plotting ATAC-seq

**Comment by Jome0169** [comment]
This also doesn't appear to be an issue with the data as when I plot this similar matrix out using deeptools the results look like... 

![deeptools_ATAC](https://user-images.githubusercontent.com/8882330/71913621-d8eaea80-3145-11ea-8890-39b752de3a14.png)

**Comment by jokergoo** [comment]
It is because the default ordering method orders rows by the average distance from signals  to the target (the TSS).

**Comment by Jome0169** [comment]
@jokergoo Yep! That's it. Thank you so much.
