### ISSUE TITLE
Problem splitting by more than two groups in newest version (1.18.0)

### ISSUE THREAD

**Issue by dougbarrows** [jokergoo/EnrichedHeatmap#47]
Hello - 

Love the package. We have integrated it into our Bioconductor package 'profileplyr' and it's really powerful - thanks! 

However, since I have updated to the newest version of Bioconductor (v3.11 with R4.0) and the newest version of EnrichedHeatmap (1.18.0) I have noticed an issue whenever I try and split the rows by more than two groups within the EnrichedHeatmap() function. Using code from the example in the help section of the function with a few modifications to add a vector to split by, I get strange results with three groups. When I try and split into three groups, the third group is not shown in the figure. Also, when I run the same exact code with the previous version of the package (1.16.0) I get the expected result.  

The code to produce this result is shown below, and below the code I have pasted the results for the heatmap split into two and three groups using version 1.18.0 of the package, and the heatmap split into three groups using version 1.16.0 of the package, which looks correct.

Thanks for your help!

```
load(system.file("extdata", "chr21_test_data.RData", package = "EnrichedHeatmap"))
mat3 = normalizeToMatrix(meth, cgi, value_column = "meth", mean_mode = "absolute",
                         extend = 5000, w = 50, smooth = TRUE)

group_2 <- as.factor(c(rep(1, 100), rep(2,265)))
ht_2 <- EnrichedHeatmap(mat3, name = "methylation", column_title = "methylation near CGI", row_gap =  unit(2, "mm"), row_split = group_2)

group_3 <- as.factor(c(rep(1, 100), rep(2,100), rep(3, 165)))
ht_3 <- EnrichedHeatmap(mat3, name = "methylation", column_title = "methylation near CGI", row_gap =  unit(2, "mm"), row_split = group_3)

```
Result for 'ht_2' above (split into two groups) with EnrichedHeatmap 1.18.0 (looks normal): 
![image](https://user-images.githubusercontent.com/25552623/80617137-bb50d200-8a0f-11ea-930e-331fbef675a3.png)

Result for 'ht_3' above (split into three groups) with EnrichedHeatmap 1.18.0 (only two of the three groups are shown): 
![EH_test_1 18_threeGroups](https://user-images.githubusercontent.com/25552623/80617496-2e5a4880-8a10-11ea-8ca8-0da98e2b0ad1.png)

Result for 'ht_3' above (split into three groups) with EnrichedHeatmap 1.16.0 (expected result): 
![EH_test_1 16_threeGroups](https://user-images.githubusercontent.com/25552623/80617629-58136f80-8a10-11ea-900e-ff6e4605a17a.png)

**Comment by jokergoo** [comment]
This is due to the new grid 4.0 package. I have fixed it and you can update the package by:

```{r}
library(devtools)
install_github("jokergoo/ComplexHeatmap")
install_github("jokergoo/EnrichedHeatmap")
```

You can also use `BioManager::install()`, but it takes several days to synchronize to bioconductor.

**Comment by dougbarrows** [comment]
Thank you! That fixed it.
