### ISSUE TITLE
Height of column title box

### ISSUE THREAD

**Issue by dktanwar** [jokergoo/EnrichedHeatmap#48]
Hi @jokergoo 

How can I change the height of the column title box?

![Screenshot 2020-08-13 at 11 56 24](https://user-images.githubusercontent.com/8986859/90121244-0b079f00-dd5c-11ea-91ba-7da41859f5db.png)

I tried:

```r
column_title_gp = gpar(box_height = unit(5, "mm"))
```

```r
column_title_gp = gpar(height = unit(5, "mm"))
```

```r
ht_opt$simple_anno_size <- unit(2, "mm")
```

**Nothing worked!**

**Comment by jokergoo** [comment]
Do want to fix the font size while just increase the height where the title sits? Then you can do e.g.:

```r
ht_opt$TITLE_PADDING = unit(5, "mm")
```

before the call of `Heatmap()` function.

**Comment by dktanwar** [comment]
Thank you, @jokergoo!
So, if I understood correctly, you are trying to reduce the padding across the title.

**Doesn't seem to be working!**

```r
library(EnrichedHeatmap)

set.seed(123)
load(system.file("extdata", "chr21_test_data.RData", package = "EnrichedHeatmap"))

tss <- promoters(genes, upstream = 0, downstream = 1)

mat1 <- normalizeToMatrix(H3K4me3, tss,
  value_column = "coverage",
  extend = 5000, mean_mode = "w0", w = 50
)
```

```r
ht_opt$TITLE_PADDING <- unit(1, "mm")
EnrichedHeatmap(mat1,
  name = "H3K4me3", ,
  column_title = "H3K4me3",
  column_title_gp = gpar(fontfamily = "Helvetica", fontsize = 6, fill = "grey")
)
```
![Screenshot 2020-08-13 at 13 01 26](https://user-images.githubusercontent.com/8986859/90127291-3e026080-dd65-11ea-8405-d0b676e86bd1.png)

```r
ht_opt$TITLE_PADDING <- unit(20, "mm")
EnrichedHeatmap(mat1,
                name = "H3K4me3", ,
                column_title = "H3K4me3",
                column_title_gp = gpar(fontfamily = "Helvetica", fontsize = 6, fill = "grey")
)
```
![Screenshot 2020-08-13 at 13 02 01](https://user-images.githubusercontent.com/8986859/90127301-42c71480-dd65-11ea-8f11-e1bb2a0e0f44.png)


**Am I doing something wrong here?**

**Comment by jokergoo** [comment]
Then update both ComplexHeatmap and EnrichedHeatmap to the newest versions (from GitHub). See the following plot from my side:

![image](https://user-images.githubusercontent.com/449218/90128720-a18d8d80-dd67-11ea-9b66-d652d25dd706.png)

**Comment by dktanwar** [comment]
Ah! 

Solved!

Thank you so much!
