### ISSUE TITLE
Question: Setting `lwd` for all heatmaps

### ISSUE THREAD

**Issue by dktanwar** [jokergoo/EnrichedHeatmap#49]
Is it possible to set `lwd` to everything on an EnrichedHeatmap?

I tried 

`border_gp = gpar(col = "black", lwd = 0.4)`
I would like to set it for `top_annotation`, `column_title` border, and `x-axis`.

**Comment by jokergoo** [comment]
There is no parameter for globally controlling the graphic parameters, but in **grid**, all the children viewports inherit the graphic parameters from parent viewport, so you do like this:

```r
grid.newpage()
pushViewport(viewport(gp = gpar(lwd = 0.1)))
draw(enrichedHeatmap(...), newpage = FALSE)
popViewport()
```

**Comment by dktanwar** [comment]
Amazing!

Thank you so much!
