### ISSUE TITLE
impute DNA methylation when there is no CpG

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/EnrichedHeatmap#5]
Hi,

I saw in the tutorial, when there is no CpG, it can be represented as NA or fit by `locfit`
If you can read this post https://liorpachter.wordpress.com/2015/07/13/how-to-average-genome-wide-data/

and maybe you can take advantage of their tool called [COMPARE](http://bio.math.berkeley.edu/COMPARE/) to impute the missing values. I am not sure their method is similar to `locfit` or not...I am not a mathematical person :) 

Best,
Ming

**Comment by jokergoo** [comment]
Thanks for this information. I will surely check it out!

**Comment by jokergoo** [comment]
I cannot find this tool so I won't consider it...
