### ISSUE TITLE
annotation_legend_side does not work

### ISSUE THREAD

**Issue by dktanwar** [jokergoo/EnrichedHeatmap#50]
Hi @jokergoo 

It seems like the `annotation_legend_side` option is not working with EnrichedHeatmap. Seems like row annotations legends are treated as heatmap legends.

## Example

```r
library(EnrichedHeatmap)

set.seed(123)
load(system.file("extdata", "chr21_test_data.RData", package = "EnrichedHeatmap"))

tss <- promoters(genes, upstream = 0, downstream = 1)

mat1 <- normalizeToMatrix(H3K4me3, tss,
  value_column = "coverage",
  extend = 5000, mean_mode = "w0", w = 50
)[1:100,]

k <- kmeans(x = mat1, centers = 2)$cluster
k[k == 1] <- "A"
k[k == 2] <- "B"

la <- HeatmapAnnotation(
  Categories = k,
  which = "row"
)

ht <- EnrichedHeatmap(mat1,
  km = 2,
  left_annotation = la,
  name = "H3K4me3", ,
  column_title = "H3K4me3",
  column_title_gp = gpar(fill = "grey")
)
```

### `annotation_legend_side`

```r
draw(ht, annotation_legend_side = "bottom")
```
![Screenshot 2020-08-14 at 10 51 22](https://user-images.githubusercontent.com/8986859/90231906-233ef300-de1c-11ea-90b1-134468a6cf0e.png)

### `heatmap_legend_side`

```r
draw(ht, heatmap_legend_side = "bottom")
```

![Screenshot 2020-08-14 at 10 51 00](https://user-images.githubusercontent.com/8986859/90231893-1fab6c00-de1c-11ea-97dc-eac411dabaca.png)

**Comment by jokergoo** [comment]
This is a little bit confusing. The row annotation legend is actually "heatmap annotation legend" because it is always put together with heatmap legends.

**Comment by dktanwar** [comment]
OK. So, is there a way to put the color key (H3K4me3) of Heatmaps at the bottom and row and column annotations legends on right?

**Comment by jokergoo** [comment]
Well, there is a way but I don't think it is very straightforward to understand. You can convert the heatmap to a "vertically concatenated heatmap". Under this scenario, the legends of row annotations are not grouped with heatmap legends (because now the major direction to read the heatmap is from top to bottom) and `annotation_legend_side` can be used to control them.

```r
ht = ht %v% NULL # add to a null heatmap to mark it as a vertically concatenated heatmap
draw(ht, annotation_heatmap_legend = "right", heatmap_legend_side = "bottom")
```

**Comment by dktanwar** [comment]
Thank you!

**Comment by dktanwar** [comment]
And, what you meant is:

```r
draw(ht, annotation_legend_side = "right", heatmap_legend_side = "bottom")
```

**Comment by jokergoo** [comment]
Yes, that was a typo!
