### ISSUE TITLE
Setting number of breaks

### ISSUE THREAD

**Issue by dktanwar** [jokergoo/EnrichedHeatmap#51]
Hi @jokergoo 

**Is it possible to set the number of breaks for the color key?**

## Example

```r
library(EnrichedHeatmap)

set.seed(123)
load(system.file("extdata", "chr21_test_data.RData", package = "EnrichedHeatmap"))

tss <- promoters(genes, upstream = 0, downstream = 1)

mat1 <- normalizeToMatrix(H3K4me3, tss,
  value_column = "coverage",
  extend = 5000, mean_mode = "w0", w = 50
)[1:100,]

k <- kmeans(x = mat1, centers = 2)$cluster
k[k == 1] <- "A"
k[k == 2] <- "B"

la <- HeatmapAnnotation(
  Categories = k,
  which = "row"
)

ht <- EnrichedHeatmap(mat1,
  km = 2,
  left_annotation = la,
  name = "H3K4me3", ,
  column_title = "H3K4me3",
  column_title_gp = gpar(fill = "grey")
)
```

### Heatmap

```r
draw(ht, annotation_legend_side = "bottom")
```
![Screenshot 2020-08-14 at 10 51 22](https://user-images.githubusercontent.com/8986859/90231906-233ef300-de1c-11ea-90b1-134468a6cf0e.png)

### Heatmap with 3 breaks

```r
ht@matrix_color_mapping@colors <- ht@matrix_color_mapping@colors[c(1,2,4)]
ht@matrix_color_mapping@levels <- ht@matrix_color_mapping@levels[c(1,2,4)]

draw(ht, heatmap_legend_side = "bottom")
```

![Screenshot 2020-08-18 at 11 49 59](https://user-images.githubusercontent.com/8986859/90498738-f99e0880-e148-11ea-83cb-e8ed974d6108.png)

**Is there a way to provide the number of breaks?**

### I am aware of

```r
heatmap_legend_param = list(
      at = c(0, 20, 60),
      title = H3K4me3
)
```

But, it would be good to know the possibility of defining the number of breaks.

**Comment by dktanwar** [comment]
Also, is it possible to define the number of breaks for `anno_enriched`?

**Comment by jokergoo** [comment]
```r
heatmap_legend_param = list(
      at = c(0, 20, 40, 60, 80),
      title = H3K4me3
)
```

and 

```r
anno_enriched(..., axis_param = list(at = c(0, 10, 20, 30, 40, 50, 60, 70, 80)))
```

**Comment by dktanwar** [comment]
Yes, I am aware of these options. But, when I have a number of heatmaps to be plotted, it's a bit of more work to specify for each heatmap. Hence, I wanted to know if it is possible to just specify the number of breaks. Like, I just say `n_break = 3`.

Would this be a possibility?

**Comment by jokergoo** [comment]
Ah, no, this is impossible. The number of breaks is automatically inferred from the distribution of the data points.

**Comment by dktanwar** [comment]
Hi @jokergoo 

Is it possible to know the `at` values from the matrix?

Currently, the only possible way for me to get the `at` values is by first making the heatmap and then specifying values to `at`. How to already know it without plotting the heatmap.

If I would know the `min` and `max`, I can calculate the mean. Is it possible to obtain from the matrix?

I already tried `min` and `max` R functions, but the values I get and the values on the color scale does not match. I also tried via `rowMeans`

**Comment by jokergoo** [comment]
Why do need to know `at` values before making the heatmap? Is there any specific reason for that?

You can see how `at` is calculated from the following lines:

https://github.com/jokergoo/ComplexHeatmap/blob/aa5ea637cbd75e9c8b5bf79e875853fd6445ddd4/R/ColorMapping-class.R#L96-L106

**Comment by dktanwar** [comment]
Yes, I have a reason for that: it will help me in properly defining the number of breaks.

Let's say the current heatmap has 6 breaks at 0, 10, 20, 30, 40, and 50. Now, if I want to have just 3 breaks at 0, 25, and 50, knowing the `min` and `max` breaks would be helpful. So that I can parse it to `at = c(0, 25, 50)`

**Comment by jokergoo** [comment]
The breaks are inferred from the values in the matrix that tries to be integers and cover most of the values in the matrix. If you want to have the breaks before making the heatmap, you can calculate it by your own based on the value distribution in the matrix. 

Following functions might be helpful: `pretty()` and `grid.pretty()`.

**Comment by dktanwar** [comment]
Thank you! I will check these functions...
