### ISSUE TITLE
how to use row_split and add annotation heatmap for the split

### ISSUE THREAD

**Issue by olechnwin** [jokergoo/EnrichedHeatmap#52]
Hello,

I'm using `row_split` to divide the heatmap into three sections which I then annotate by adding another heatmap (mimicking the code [here](https://github.com/jokergoo/EnrichedHeatmap)). However, the rows of the heatmap is no longer sorted when I added the heatmap annotation.
I have uploaded the image to run the code below: [test_heatmap.RData](https://www.dropbox.com/s/5lt13hfzohvss7y/test_heatmap.RData?dl=0)
These are the codes I ran:
```
tss <- promoters(rna.ref.genes,upstream=0,downstream=1)
mat1=normalizeToMatrix(bw.gr,tss,value_column = "score",extend=5000, mean_mode = "w0", w = 50)
# heatmap with mean values across tss
axis_name = c("-5kb", "TSS", "5kb")
hm0=Heatmap(expr.102.not.85, 
 col = 2:4,name="Reg. by",show_row_names = FALSE,width=unit(3,"mm"))
hm1 = EnrichedHeatmap(mat1,column_title_gp = gpar(fontsize = 10),
 top_annotation = HeatmapAnnotation(lines=anno_enriched(gp=gpar(col=2:4,lwd=1.5))),
 axis_name=axis_name,
 show_row_names = FALSE)
draw(hm1,row_split=expr.102.not.85)
```
If I don't draw hm1, the rows of heatmap are sorted inside each section, which is what I wanted.
![image](https://user-images.githubusercontent.com/20069067/92520278-59884c00-f1e9-11ea-83f3-839767b559f1.png)
However if I changed the last line above to:

`draw(hm0+hm1,row_split=expr.102.not.85)`

The rows of heatmap is no longer sorted. How do I keep the rows sorted? Also, how do I supress the labels on the far left?
![image](https://user-images.githubusercontent.com/20069067/92520042-fdbdc300-f1e8-11ea-8af5-5ff6f3e9791e.png)

Thank you in advance for your help.

**Comment by olechnwin** [comment]
Ah...I figured out what went wrong. It was following the row order of the first heatmap.
If I switched the order `draw(hm1+hm0,row_split=expr.102.not.85)` then hm1 heatmap will still be sorted and split.

Is there a way I can still draw the `hm0` on the left and keep `hm1` sorted? Also, I still haven't figured out how to remove the text annotation on the left.
![image](https://user-images.githubusercontent.com/20069067/92524951-f7cbe000-f1f0-11ea-9779-0aef9a2cde01.png)

**Comment by jokergoo** [comment]
I am sorry for the late reply. I miss this issue because tons of issues from my other projects :)

You can set `main_heatmap` argument to decide which heatmap controls the row order of all heatmap list:

```r
draw(hm0+ hm1, main_heatmap = "name-of-hm1")  # give hm1 a name!
```

To remove the row titles, set `row_title = NULL`

```r
hm1 = EnrichedHeatmap(..., row_title = NULL)
```

**Comment by olechnwin** [comment]
I really appreciate you're still taking the time to reply. It's still useful for me :-)

Thanks! I missed the `main_heatmap` parameter. That's really helpful. 

Weirdly, I somehow managed to find `row_title_gp` so I set the size to 0 but not `row_title` ha! Thanks!!
