### ISSUE TITLE
Trouble with scaling

### ISSUE THREAD

**Issue by wilsoner2175** [jokergoo/EnrichedHeatmap#56]
Hi,

Thank you for creating this incredibly useful tool!

I'm having a bit of trouble with the scaling of values/colors in my heatmaps--rather than ranging from 0 to xx, I'm getting scales that go from negative numbers to xx. 

I'm trying to plot ChIPseq data for three different groups for a given modification in one plot. To do this I've concatenated separately normalized matrices and have tried splitting rows based on the number of rows associated with each group. When I plot using EnrichedHeatmap, I get some wacky looking plots with scales that go into the negative. Ideally, zero would be white rather than light red on these plots to accentuate the signal. I'm also curious if there's a way to order the groups in  heatmap--ie sample A at the top, B in the middle, and C at the bottom. I've included a few examples plots here and the basic code I'm using to create them.

[sample_Data.pdf](https://github.com/jokergoo/EnrichedHeatmap/files/5832282/sample_Data.pdf)

Please let me know if there is something I'm doing wrong here, or if there is a better way to accomplish my goal of plotting separate groups (over the same intervals) in the the same plot. I'm concerned that normalizing each matrix separately and then concatenating may be a source of this error, but I'm unsure. 

Any info or advice you have would be much appreciated! Thank you in advance for you time!

colors <- gpar(col = c('blue', 'green', 'red'))

mat1 <- normalizeToMatrix(H3K27_primary_sum.gr, IDH1and2_dss_DMRS_woTET.gr, value_column = "count", 
    extend = 5000, mean_mode = "w0", w = 10, keep= c(0,0.99),smooth=T)
mat2 <- normalizeToMatrix(H3K27_IDHm_sum.gr, IDH1and2_dss_DMRS_woTET.gr, value_column = "count", 
    extend = 5000, mean_mode = "w0", w = 10, keep= c(0,0.99),smooth = T)
mat3 <- normalizeToMatrix(H3K27_CD34_sum.gr, IDH1and2_dss_DMRS_woTET.gr, value_column = "count", 
    extend = 5000, mean_mode = "w0", w = 10, keep= c(0,0.99),smooth=T)

H3K27<-rbind(mat1,mat2,mat3)

EnrichedHeatmap(H3K27, col= c("white", "red"), name = "H3K27", row_split = c(rep("IDHwt", length(IDH1and2_dss_DMRS_woTET.gr)),rep("IDHmut", length(IDH1and2_dss_DMRS_woTET.gr)),rep("CD34", length(IDH1and2_dss_DMRS_woTET.gr))), column_title="H3K27 over IDHm dmrs",top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = c(1:3)))))

**Comment by jokergoo** [comment]
Can you print the output from 

```r
quantile(H3K27_primary_sum.gr$count)
quantile(mat1)
```

I feel it is from smoothing.

**Comment by wilsoner2175** [comment]
The output from quantile(H3K27_primary_sum.gr$count) is:

         0%         25%         50%         75%        100% 
   0.000000    0.469329    0.728766    1.186832 7682.348429 

The output from quantile(mat1) is:

         0%         25%         50%         75%        100% 
-20.8501352   0.7857693   1.4880258   3.3676350  21.9518625

Is it best to not perform the smoothing in this case? And do you know what would cause the smoothing to give the negative values?

Thanks,
Ellie

**Comment by jokergoo** [comment]
I would suggest not to apply smoothing for chipseq data. It is more proper for methylation data where the signal is single-basepair wise.

However, this needs to be improved that the color mapping should not take negative values. I will improve that.

**Comment by jokergoo** [comment]
As a quick fix, can you manually set the color mapping as, e.g.:

```r
EnrichedHeatmap(H3K27, col= colorRamp2(0, quantile(H3K27, 0.99)), c("white", "red"))
```

**Comment by wilsoner2175** [comment]
Great, yes that worked! Thank you for your help and for maintaining this tool!

Best,
Ellie
