### ISSUE TITLE
Can't get the picture

### ISSUE THREAD

**Issue by chenchen-eng** [jokergoo/EnrichedHeatmap#59]
Error in getFromNamespace(device_info[3], ns = device_info[2])(temp_image) : 
  unable to open C:\Users\鏉嶾AppData\Local\Temp\Rtmpqg5WDE\.heatmap_body_matrix_2_1_140787acc91.png

**Comment by jokergoo** [comment]
try to run `dev.off()` several times and remake the plot.

**Comment by Isabelle-C** [comment]
Hi, I know this issue has been closed, but I ran into the same problem. Running dev.off() multiple times did't solve my problem. However, I was able to run it after installing xquartz via`brew install --cask xquartz` in terminal. My computer is macpro with M1 chip. I just want to post this, in case it would be useful to others. Thank you!

**Comment by liboxun** [comment]
I had the same issue, which was solved by following @Isabelle-C's suggestion. 

However I wasn't able to install xquartz via `brew` for certain reasons, but downloading and installing the `.pkg` from https://www.xquartz.org/ also solved the problem for me.

**Comment by Franelizabethgalvez** [comment]
Hi, I have the same problem with a MacBook pro M2, I installed https://www.xquartz.org/ and solved the problem, thanks @liboxun and @Isabelle-C
