### ISSUE TITLE
strand information

### ISSUE THREAD

**Issue by MorillonLab** [jokergoo/EnrichedHeatmap#66]
Hi ,

Thank you for the package ! I have checked many examples of heatmaps, and I have only seen those related to histone marks (no strand infos for the signal) ; is the strand information at the signal side taken into account, or is it only on the region side ? I would like to plot coverage from RNAseq, and it seems that no matter the strand of the signal, the output is the same. Is there a way to enforce the strand information at both sides ?

thank you in advance !

Marc G.

**Comment by jokergoo** [comment]
The strand information is considered if the Granges object has it. E.g., upstream of TSS is the 'real' upstream.
