### ISSUE TITLE
Visualize multiple target regions in one graph

### ISSUE THREAD

**Issue by xfchen0912** [jokergoo/EnrichedHeatmap#68]
Hello, Thank you for the useful package!
I wonder if there is a way to visualize multiple target regions in one graph.
In my case I have three gene groups with different labels and I want to compare them in one graph.
Maybe like this, but I want different labels present gene groups not signals
![image](https://user-images.githubusercontent.com/92902438/167760340-652b0f87-c14b-46de-9e44-b581515dd298.png)

**Comment by jokergoo** [comment]
Very nice suggestion! I will support it soon.
