### ISSUE TITLE
How To? color top annotation lines by row_split variable?

### ISSUE THREAD

**Issue by malcook** [jokergoo/EnrichedHeatmap#69]
I see that `anno_enriched`'s gpar parameter is used to set the color of all the lines appearing in a `top_annotation`.

I would rather like each line to encode the the row_split variable (in my cases,  a "cluster" identifier).

Is it possible within your framework?

**Comment by jokergoo** [comment]
Then I think you can jus set a color vector to `gp` in `anno_enrich()`.

**Comment by malcook** [comment]
Thanks, Yes, this works ok for a single heatmap.

If however I have an `HeatmapList` of `ComplexHeatmap`s, and I `ComplexHeatmap::draw` it repeatedly with different values for          `row_split ` (exploring the effect of different clustering algos on the underlying data), is there some way to reset the top annotation's gpar accordingly?
